### PR TITLE
Fixed Windows tests

### LINKED ISSUE #6: Windows tests
Currently many of the `gulp unit-test` tests fail on Windows.

We will need to writing .bat equivalents of the .sh scripts.

### PR DESCRIPTION
**Pull request by scottdixon**
This PR addresses most of the windows issues.

Windows still has a hard time `.spawn`ing if both the cmd path and an argument contain spaces.

There are no quick-fixes that suit us at this stage without rewriting how we handle processes. Looks like it has recently been addressed: https://github.com/nodejs/node/pull/4598

Resolves #6

CC @imurchie

### CODE REVIEW

File: test/helpers.js [hunk 1]
```diff
@@ -1,8 +1,12 @@
...
+  // Append .bat or .sh is there's no extention
+  if (fix.indexOf('.') === -1) {
+    fix = fix + (system.isWindows() ? '.bat' : '.sh');
+  }
   return path.resolve(__dirname, "..", "..", "test", "fixtures", fix);
 }
 
-export { getFixture };
-
+export { getFixture, system };
```
Comment (imurchie) [inline test/helpers.js]: I'd rather other modules just import `system` from `appium-support`, rather than passing it around like this.

Comment (scottdixon) [inline test/helpers.js]: Thanks. Updated.
